[tool.poetry]
name = "pyroll-basic"
version = "1.0.1"
description = "A meta package for installing quickly the PyRolL core and a set of basic plugins."
authors = ["Max Weiner <max.weiner@imf.tu-freiberg.de>"]
license = "BSD-3-Clause"
homepage = "https://pyroll-project.github.io"
repository = "https://github.com/pyroll-project/pyroll-core"
documentation = "https://pyroll.readthedocs.io/en/latest"
readme = "README.md"
packages = [
    {include = "pyroll/basic.py" }
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Manufacturing",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering"
]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
pyroll = "^1.0.1"
pyroll-integral-thermal = "^1.1.0"
pyroll-hensel-power-and-labour = "^1.0.0"
pyroll-wusatowski-spreading = "^1.1.0"
pyroll-zouhar-contact = "^1.0.0"
pyroll-freiberg-flow-stress = "^1.1.1"
pyroll-hitchcock-roll-flattening = "^1.0.0"
pyroll-lendl-equivalent-method = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
