[tool.poetry]
name = "pyroll-basic"
version = "2.0"
description = "A meta package for installing quickly the PyRolL core and a set of basic plugins and extensions."
authors = ["Max Weiner <max.weiner@imf.tu-freiberg.de>"]
license = "BSD-3-Clause"
homepage = "https://pyroll-project.github.io"
repository = "https://github.com/pyroll-project/pyroll-core"
documentation = "https://pyroll.readthedocs.io/en/latest"
readme = "README.md"
packages = [
    {include = "pyroll/basic.py" }
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Manufacturing",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering"
]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
pyroll-core = "^2.0"
pyroll-cli = "^2.0"
pyroll-report = "^2.0"
pyroll-export = "^2.0"
pyroll-integral-thermal = "^2.0"
pyroll-hensel-power-and-labour = "^2.0"
pyroll-wusatowski-spreading = "^2.0"
pyroll-zouhar-contact = "^2.0"
pyroll-freiberg-flow-stress = "^2.0"
pyroll-hitchcock-roll-flattening = "^2.0"
pyroll-lendl-equivalent-method = "^2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
